logLevel = "ERROR"
defaultEntryPoints = ["http", "https"]

# [entryPoints]
#   [entryPoints.http]
#   address = ":80"
#     [entryPoints.http.redirect]
#     regex = "^http://(.*)"
#     replacement = "https://$1"
#   [entryPoints.https]
#   address = ":443"
#     [entryPoints.https.tls]

[web]
address = ":8888"
ReadOnly = true

# [acme]
# email = "chris@webcanvas.com.au"
# storageFile = "acme.json"
# entryPoint = "https"
# [[acme.domains]]
#   main = "quarkstar.lan"
#   sans = [
#   "plex.quarkstar.lan",
#   "sabnzb.quarkstar.lan",
#   ]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "quarkstar.lan"
watch = true
